name: "Deploy Monster Hunter Mod Manager"

on:
  push:
    tags:
      - "monster-hunter-mod-manager/v*"

env:
  PROJECT_PATH: src/MonsterHunterModManager.WpfApp/MonsterHunterModManager.WpfApp.csproj

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - run: dotnet restore ${{ env.PROJECT_PATH }}
        
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore -r win-x64 -p:PublishSingleFile=true
        
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: vimtor/action-zip@v1
        with:
          files: src/MonsterHunterModManager.WpfApp/bin/Release/net6.0-windows/win-x64/publish/
          recursive: true
          dest: "Monster Hunter Mod Manager.zip"

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "Monster Hunter Mod Manager.zip"
          release-url: ${{ steps.create_release.outputs.upload_url }}